site_name: AP Biology - An Interactive Course
repo_url: https://github.com/dmccreary/biology
site_url: https://dmccreary.github.io/biology/
site_description: An interactive intelligent textbook for AP Biology designed for college credit.
site_author: Dan McCreary

nav:
  - Home: index.md
  - Course Description: course-description.md

  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Graph Quality Analysis: learning-graph/quality-metrics.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Taxonomy Distribution Report: learning-graph/taxonomy-distribution.md
    - Mascot Style Guide: learning-graph/mascot-style-guide.md
    - Mascot Test: learning-graph/mascot-test.md
    - Chemical Equation Tests: learning-graph/chemical-equation-tests.md

  - MicroSims:
    - List of MicroSims: sims/index.md
    - Simple Animal Cell: sims/animal-cell/index.md   
    - Simple Plant Cell: sims/plant-cell/index.md 
    - Chemical Equation Rendering: sims/chemical-equation-rendering/index.md

  - License: license.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'green'
    accent: 'white'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer
    - content.action.edit

plugins:
  - search
  - social
  - social_override

markdown_extensions:
  - md_in_html
  - attr_list
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - css/extra.css
  - css/mascot.css

extra_javascript:
  - js/extra.js
  - js/mathjax-config.js
  # For a Biology textbook we use chemistry equations
  # We add the chemical markdown extension to MathJax
  # It is not included in the default MathJax bundle, so we need to load the full TeX bundle
  - https://unpkg.com/mathjax@3/es5/tex-chtml.js

# Watch these files for changes to trigger a rebuild
watch:
  - docs
  - mkdocs.yml

copyright: Copyright &copy; 2025 Dan McCreary. Licensed under <a href="license/">CC BY-NC-SA 4.0</a> for non-commercial use.

extra:
  generator: false  # remove the default "Made with MkDocs" footer

  # Google Analytics configuration
  analytics:
    provider: google
    property: G-MF2R7QQ4Q2
  # this book conforms to the v1 schema for intelligent textbooks
  schema: https://dmccreary.github.io/intelligent-textbooks/ns/textbook/v1
  textbook_name: Biology
  textbook_version: "1.0"
